version: '3'

services: 
  app: 
    build: .
    command: npm start
    ports: 
      - '8085:8085'
    volumes:
      - .:/usr/app

  db:
    container_name: 'database-sisnota'
    image: mariadb
    restart: always
    ports: 
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
